/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CTokenInterface } from "./CTokenInterface";
export type { ComptrollerInterface } from "./ComptrollerInterface";
export type { LiquidityMiningInterface } from "./LiquidityMiningInterface";
