/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  TokenErrorReporter,
  TokenErrorReporterInterface,
} from "../../../../contracts/compound-protocol/ErrorReporter.sol/TokenErrorReporter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "error",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "info",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "detail",
        type: "uint256",
      },
    ],
    name: "Failure",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603e80601d6000396000f3fe6080604052600080fdfea265627a7a72315820faee74c5a89a91069c79357165400abbdf5dc2e828a7d1f21a981ffb6549d84d64736f6c63430005110032";

type TokenErrorReporterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TokenErrorReporterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TokenErrorReporter__factory extends ContractFactory {
  constructor(...args: TokenErrorReporterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<TokenErrorReporter> {
    return super.deploy(overrides || {}) as Promise<TokenErrorReporter>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): TokenErrorReporter {
    return super.attach(address) as TokenErrorReporter;
  }
  override connect(signer: Signer): TokenErrorReporter__factory {
    return super.connect(signer) as TokenErrorReporter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TokenErrorReporterInterface {
    return new utils.Interface(_abi) as TokenErrorReporterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenErrorReporter {
    return new Contract(address, _abi, signerOrProvider) as TokenErrorReporter;
  }
}
