/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CWrappedNative } from "./CWrappedNative";
export type { WrappedNativeInterface } from "./WrappedNativeInterface";
