/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  XSushiExchangeRateInterface,
  XSushiExchangeRateInterfaceInterface,
} from "../../../../../contracts/compound-protocol/PriceOracle/interfaces/XSushiExchangeRateInterface";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getExchangeRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class XSushiExchangeRateInterface__factory {
  static readonly abi = _abi;
  static createInterface(): XSushiExchangeRateInterfaceInterface {
    return new utils.Interface(_abi) as XSushiExchangeRateInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): XSushiExchangeRateInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as XSushiExchangeRateInterface;
  }
}
