/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITokenInterface } from "./ITokenInterface";
export type { StakingRewardsFactoryInterface } from "./StakingRewardsFactoryInterface";
export type { StakingRewardsInterface } from "./StakingRewardsInterface";
